services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/production/nginx/Dockerfile
    restart: unless-stopped
    volumes:
      - cyberland-app-production:/var/www:ro               # Shared app build volume
    networks:
      - cyberland-production
    ports:
      - "8080:80"
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/production/php-fpm/Dockerfile
      target: production
    restart: unless-stopped
    volumes:
      - cyberland-app-production:/var/www                  # Shared app build volume
      - ./storage-init:/var/www/storage-init:ro            # Seed files
      - cyberland-storage-production:/var/www/storage      # Persistent volume for Laravel storage
      - ./.env:/var/www/.env:ro                            # Laravel .env file
    env_file:
      - .env
    networks:
      - cyberland-production
    depends_on:
      - db
    user: root
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    command: ["php-fpm"]

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - cyberland-production
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  cyberland-production:

volumes:
  db-data:
  cyberland-storage-production:
  cyberland-app-production:
