services:
  app:
    build:
      context: .
      dockerfile: docker/production/php-fpm/Dockerfile
    networks:
      - cyberland-network
    depends_on:
      - db

  web:
    image: nginx:alpine
    volumes:
      - ./docker/production/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "7000:80"
    depends_on:
      - app
    networks:
      - cyberland-network

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - cyberland-network

networks:
  cyberland-network:
    driver: bridge

volumes:
  db-data:
